const express = require("express");
const mongoose = require("mongoose");
const QRCode = require("qrcode");
const Ticket = require("./models/Ticket");
const Attendance = require("./models/Attendance");
const cors = require("cors");
const PDFDocument = require("pdfkit");
const app = express();


app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cors());
app.set("view engine", "ejs");
app.use(express.static("public"));

// MongoDB Connection
mongoose.connect("mongodb://127.0.0.1:27017/eventdb")
.then(() => {
    console.log("MongoDB Connected");
})
.catch((err) => {
    console.log(err);
});

// Registration Form
app.get("/", (req, res) => {
    res.render("register");
});

// Register User
app.post("/register", async (req, res) => {

    try {

        const { name, email, eventName } = req.body;

        // Unique Ticket ID
        const ticketId = "TKT" + Date.now();

        // QR Code Data
        const qrData = ticketId;

        // Generate QR
        const qrCode = await QRCode.toDataURL(qrData);

        // Save in MongoDB
        const ticket = new Ticket({
            name,
            email,
            eventName,
            ticketId,
            qrCode
        });

        await ticket.save();

        // Show Ticket Page
        res.render("ticket", { ticket });

    } catch (error) {

        console.log(error);
        res.send("Error Occurred");

    }

});
app.get("/download/:id", async (req, res) => {

    const ticket = await Ticket.findById(req.params.id);

    const PDFDocument = require("pdfkit");
    const doc = new PDFDocument({
        size: "A4",
        margin: 40
    });

    res.setHeader(
        "Content-Disposition",
        `attachment; filename=${ticket.ticketId}.pdf`
    );

    res.setHeader("Content-Type", "application/pdf");

    doc.pipe(res);

    // HEADER
    doc.rect(0, 0, 595, 80)
        .fill("#1e3a8a");

    doc.fillColor("white")
        .fontSize(28)
        .text("EVENT TICKET", 0, 25, {
            align: "center"
        });

    // MAIN CARD
    doc.roundedRect(40, 110, 515, 420, 15)
        .lineWidth(2)
        .stroke("#3b82f6");

    // EVENT TITLE
    doc.fillColor("#2563eb")
        .fontSize(18)
        .text("TECH FEST 2025", 70, 140);

    // DETAILS
    doc.fillColor("black")
        .fontSize(14);

    doc.text(`Name: ${ticket.name}`, 70, 190);

    doc.text(`Email: ${ticket.email}`, 70, 225);

    doc.text(`Event: ${ticket.eventName}`, 70, 260);

    doc.text(`Ticket ID: ${ticket.ticketId}`, 70, 295);

    // Divider
    doc.moveTo(350, 140)
        .lineTo(350, 450)
        .dash(5, { space: 5 })
        .stroke();

    doc.undash();

    // QR Heading
    doc.fillColor("#6b7280")
        .fontSize(12)
        .text("SCAN FOR ENTRY", 390, 150);

    // QR IMAGE
    const qrImage = Buffer.from(
        ticket.qrCode.split(",")[1],
        "base64"
    );

    doc.image(qrImage, 380, 190, {
        width: 130
    });

    // VIP Badge
    doc.roundedRect(385, 350, 120, 40, 8)
        .fill("#8b5cf6");

    doc.fillColor("white")
        .fontSize(14)
        .text("VIP ACCESS", 405, 363);

    // Footer
    doc.rect(0, 760, 595, 40)
        .fill("#1e3a8a");

    doc.fillColor("white")
        .fontSize(10)
        .text(
            "Generated by Event Crowd Management System",
            0,
            775,
            { align: "center" }
        );

    doc.end();
});
app.post("/checkin", async (req, res) => {

    try {

        const { ticketId } = req.body;
        console.log("Received Ticket ID:", ticketId);


        const ticket = await Ticket.findOne({
            ticketId: ticketId
        });
        console.log("Found Ticket:", ticket);
        if (!ticket) {

            return res.status(404).json({
                success: false,
                message: "Invalid Ticket"
            });

        }

        const existingAttendance =
        await Attendance.findOne({
            ticketId: ticketId,
            status: "IN"
        });

        if (existingAttendance) {

            return res.json({
                success: false,
                message: "Already Entered"
            });

        }

        const attendance =
        new Attendance({

            ticketId: ticket.ticketId,
            name: ticket.name,
            checkInTime: new Date(),
            status: "IN"

        });

        await attendance.save();

        res.json({
            success: true,
            message: "Check-In Successful",
            name: ticket.name,
            email: ticket.email,
            event: ticket.eventName,
            ticketId: ticket.ticketId
        });

    } catch (error) {

        console.log(error);

        res.status(500).json({
            success: false,
            message: "Server Error"
        });

    }

});
app.post("/checkout", async (req, res) => {

    try {

        const { ticketId } = req.body;

        // Find active entry
        const attendance = await Attendance.findOne({
            ticketId: ticketId,
            status: "IN"
        });

        if (!attendance) {
            return res.json({
                success: false,
                message: "User not inside"
            });
        }

        // Update status
        attendance.status = "OUT";
        attendance.checkOutTime = new Date();

        await attendance.save();

        res.json({
            success: true,
            message: "Check-Out Successful",
            name: attendance.name,
            ticketId: attendance.ticketId
        });

    } catch (error) {
        console.log(error);
        res.status(500).json({
            success: false,
            message: "Server Error"
        });
    }

});
app.get("/attendance", async (req, res) => {

    try {

        const records = await Attendance.find()
        .sort({ checkInTime: -1 });

        res.json(records);

    } catch (error) {

        res.status(500).json({
            message: "Server Error"
        });

    }

});
app.post("/ticket-details", async (req, res) => {

    try {

        const { ticketId } = req.body;

        const ticket = await Ticket.findOne({
            ticketId: ticketId
        });

        if (!ticket) {

            return res.status(404).json({
                success: false,
                message: "Ticket Not Found"
            });

        }

        res.json({
            success: true,
            ticket: ticket
        });

    } catch (error) {

        console.log(error);

        res.status(500).json({
            success: false,
            message: "Server Error"
        });

    }

});
app.get("/crowd-count", async (req, res) => {

    try {

        const count = await Attendance.countDocuments({
            status: "IN"
        });

        res.json({
            success: true,
            crowdCount: count
        });

    } catch (error) {

        console.log(error);

        res.status(500).json({
            success: false,
            message: "Server Error"
        });

    }

});

// Start Server
app.listen(3000, () => {
    console.log("Server Running On Port 3000");
    console.log(" http://localhost:3000");
});